apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: http
    nodePort: 32488
  selector:
    app: hello
  type: NodePort
status:
  loadBalancer: {}
