apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 2
  serviceName: hello
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      initContainers:
        - name: status
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              rang=$(hostname|cut -d- -f 2)
              if [[ $rang = 0 ]]
              then
                echo "Primaire" > /mnt/status
              else
                echo "Secondaire n°${rang}" > /mnt/status
              fi
          volumeMounts:
            - name: status
              mountPath: /mnt

      containers:
      - image: bob2606/hello-http:0.8.33
        name: hello-http
        env:
          - name: PORT
            value: "80"
        volumeMounts:
          - name: status
            mountPath: /var/lib/hello-http/

      volumes:
        - name: status
          emptyDir:
