apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 8
      maxSurge: 100%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: bob2606/hello-http:0.8.33
        name: hello-http
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: VERSION
            value: test
        envFrom:
          - configMapRef:
              name: hello
        ports:
          - containerPort: 80
            name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: 80
          periodSeconds: 20
          failureThreshold: 2
        volumeMounts:
          - name: status
            mountPath: /var/lib/hello-http/status

      volumes:
        - name: status
          hostPath:
            path: /home/stagiaire/data/data.txt
            type: File
