---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: http-1
  name: http-1
spec:
  containers:
  - image: nginx:1.28
    name: http
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
