---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: www
  name: www
spec:
  containers:
    - image: nginx:1.28
      name: www
    - name: php
      image: php:8.2-fpm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: k8s-wk1
status: {}
